services:
  local_client:
    container_name: local_client
    image: python:3.13-slim
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python launch.py"
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    external: true

