services:
  local_client:
    container_name: local_client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./local_client:/app/local_client
    ports:
      - "5000:5000"
    networks:
      - web

networks:
  web:
    external: true

